---

- hosts: dokku
  sudo: yes

  vars:
    - dokku_version: "0.3.22"
    - dokku_vhost: "{{ hostname }}"
    - dokku_plugins: 
        - { repo: "http://github.com/ohardy/dokku-volume", name: "volume" }
        - { repo: "http://github.com/statianzo/dokku-supervisord", name: "dokku-supervisord" }
    - ssh_keys: []

  roles:
    - base
    - dokku
    - sshkeys
