---

- hosts: dokku
  sudo: yes

  vars:
    - dokku_version: "0.3.22"
    - dokku_vhost: "{{ hostname }}"
    - dokku_plugins: ["ohardy/dokku-volume", "statianzo/dokku-shoreman"]
    - sshkeys: []

  roles:
    - dependencies
    - dokku
    - sshkeys
