---

- hosts: dokku
  sudo: yes

  vars:
    - dokku_version: "0.4.3"
    - dokku_vhost: "{{ hostname }}"
    - dokku_plugins: 
        - { repo: "https://github.com/rcarmo/dokku-supervisord", name: "supervisord" }
        - { repo: "https://github.com/rcarmo/dokku-secure-apps", name: "secure-apps" }
        - { repo: "https://github.com/rcarmo/dokku-nginx-cache", name: "nginx-cache" }
    - ssh_keys: []

  roles:
    - base
    - dokku
    - sshkeys
