---


- name: prep root .ssh
  file: path=/root/.ssh state=directory mode=0700
  sudo: yes

- name: copy public key
  copy: src=~/.ssh/id_rsa.pub dest=/root/.ssh/id_rsa.pub mode=400 owner=root group=root
  sudo: yes

- name: install base packages
  apt: name={{ item }} state=latest update_cache=yes
  with_items:
    - fail2ban
    - htop
    - language-pack-en-base
    - software-properties-common
    - tmux
    - wget

- name: locale setup
  shell: locale-gen en_US.UTF-8
  shell: dpkg-reconfigure locales
  shell: update-locale {{ item }}
  with_items:
    - LANGUAGE="en_US.UTF-8"
    - LANG="en_US.UTF-8"
    - LC_ALL="en_US.UTF-8"
  sudo: yes

- name: increase file watches
  shell: sysctl -w fs.inotify.max_user_watches=100000
  sudo: yes
