---

- name: prep root .ssh
  file: path=/root/.ssh state=directory mode=0700
  sudo: yes

- name: copy public key
  copy: src=~/.ssh/id_rsa.pub dest=/root/.ssh/id_rsa.pub mode=400 owner=root group=root
  sudo: yes

- name: install dependencies
  apt: name={{ item }} state=latest update_cache=yes
  with_items:
    - tmux
    - htop
    - wget
    - software-properties-common
